from pathlib import Path
from snakemake.utils import min_version

min_version("8.13.0")


configfile: "config/config.yaml"


report: "report/workflow.rst"


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


include: "rules/common.smk"
include: "rules/datavzrd.smk"
include: "rules/enrichment.smk"
include: "rules/meta_comparisons.smk"


"""
Es muss die Spalten 'ens_gene', 'ext_gene', 'qval' geben und die Spalte mit dem Effekt muss uebergeben werden
In plot_name muss die wildcard {ns} enthalten sein

TODO:
FGSEA benoetigt sleuth output. Soll der auch in das enrichment modul?
Alle rsts
Report categories, subcategories, labels die auf wcs basieren (Vor allem fgsea_plot_gene_sets weil dort der NAme darauf basiert)
"""


rule all:
    input:
        all_input,
