from pathlib import Path
from snakemake.utils import min_version

min_version("8.13.0")


configfile: "config/config.yaml"


report: "report/workflow.rst"


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


include: "rules/common.smk"
include: "rules/datavzrd.smk"
include: "rules/enrichment.smk"
include: "rules/meta_comparisons.smk"


rule all:
    input:
        all_input,
