enrichment:
  goatools:
    # tool is only run if set to `true`
    activate: false
    fdr_genes: 0.05
    fdr_go_terms: 0.05
    effect_column: "mean_methylation"
  fgsea:
    # tool is only run if set to `true`
    activate: false
    # if activated, you need to provide a GMT file with gene sets of interest
    gene_sets_file: "resources/gene_sets/dummy.gmt"
    fdr_gene_set: 0.05
    # minimum achievable p-value  (equivalent to the reciprocal of the number of permutations, see fgsea docs)
    eps: 1.0e-50
  spia:
    # tool is only run if set to `true`
    activate: false
    # pathway database to use in SPIA, needs to be available for
    # the species specified by resources -> ref -> species above
    pathway_database: "reactome"
    # OrgDB Genome wide annotation package (https://www.bioconductor.org/packages/release/BiocViews.html#___OrgDb) for the species under consideration. Only required if you want to have a gene analysis for your pathways. Else NA
    orgDb: NA

resource:
  ontology:
    gene_ontology: "http://current.geneontology.org/ontology/go-basic.obo"
